{% set name = "dolfin-adjoint" %}
{% set version = "2023.0.0" %}
{% set post = ".post0" %}
{% set sha256 = "bd6ee31e47043d0eecd854e31761dca867fa714bd9a09330258a382521ce3e5e" %}
{% set fenics_version = "2019.1.*" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dolfin-adjoint/dolfin-adjoint/archive/refs/tags/v{{ version }}{{ post }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # patch merged upstream:

build:
  number: 1
  script: python -m pip install --no-deps .
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - fenics {{ fenics_version }}
    - moola >=0.1.6
    - scipy

test:
  requires:
    - pytest
    - pip
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - dolfin_adjoint
    - fenics_adjoint
    - pyadjoint
  commands:
    - pytest -vs tests/pyadjoint
    - pytest -vs tests/fenics_adjoint/test_optimization_scipy.py


about:
  home: https://www.dolfin-adjoint.org
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'derives the discrete adjoint and tangent linear models'

  description: |
    The dolfin-adjoint project automatically derives the discrete adjoint
    and tangent linear models from a forward model written in the Python
    interface to DOLFIN.
  doc_url: https://www.dolfin-adjoint.org/en/latest/documentation/index.html
  dev_url: https://github.org/dolfin-adjoint/dolfin-adjoint

extra:
  recipe-maintainers:
    - johannesring
    - funsim
    - minrk
